import {
  DetailListDormitory,
  DetailListUniversity,
  ListDormitory,
  ListUniversity,
  ManagerUser,
} from "../admins";
import { adminConfigRouter, configRouter } from "../config/route";
import {
  DetailInfoPassport,
  DetailMajor,
  DetailPassport,
  DetailRoom,
  DetailStudent,
  DetailUniversity,
  Dormitory,
  ElectricityLookup,
  ElectricityWater,
  Healthcare,
  Inbox,
  Passport,
  Scholarships,
  StudentRoom,
  StudentTasks,
  University,
  WaterLookup,
  Program,
  DetailProgram,
  DataStudent,
  Login,
  Sport,
  DetailSport,
  DetailTeam,
  ProfileUser,
  Notification,
} from "../pages";
const dormsRoutes = [
  { path: configRouter.home, component: Dormitory },
  { path: configRouter.studentRoom, component: StudentRoom },
  { path: configRouter.detailRoom, component: DetailRoom },
  { path: configRouter.scholarships, component: Scholarships },
  { path: configRouter.passport, component: Passport },
  { path: configRouter.detailPassport, component: DetailPassport },

  { path: configRouter.detailInfoPassport, component: DetailInfoPassport },
  { path: configRouter.electricityWater, component: ElectricityWater },
  { path: configRouter.electricityLookup, component: ElectricityLookup },
  { path: configRouter.waterLookup, component: WaterLookup },
  { path: configRouter.dataStudent, component: DataStudent },
  { path: configRouter.healthcare, component: Healthcare },
  { path: configRouter.studentTasks, component: StudentTasks },
  { path: configRouter.inbox, component: Inbox },
  { path: configRouter.program, component: Program },
  { path: configRouter.detailProgram, component: DetailProgram },
  { path: configRouter.sport, component: Sport },
  { path: configRouter.detailSportEvent, component: DetailSport },
  { path: configRouter.detailTeam, component: DetailTeam },
  { path: configRouter.profile, component: ProfileUser },
  { path: configRouter.notification, component: Notification },
];
const schRoutes = [
  { path: configRouter.home, component: University },
  { path: configRouter.detailUniversity, component: DetailUniversity },
  { path: configRouter.detailMajor, component: DetailMajor },
  { path: configRouter.detailStudent, component: DetailStudent },
  { path: configRouter.studentTasks, component: StudentTasks },
  { path: configRouter.inbox, component: Inbox },
  { path: configRouter.program, component: Program },
  { path: configRouter.detailProgram, component: DetailProgram },
  // { path: configRouter.healthcare, component: Healthcare },
  { path: configRouter.dataStudent, component: DataStudent },
  { path: configRouter.sport, component: Sport },
  { path: configRouter.profile, component: ProfileUser },
  { path: configRouter.notification, component: Notification },
];

const adminRoutes = [
  { path: adminConfigRouter.university, component: ListUniversity },
  {
    path: adminConfigRouter.detaillistuniversity,
    component: DetailListUniversity,
  },
  { path: adminConfigRouter.dormitory, component: ListDormitory },
  {
    path: adminConfigRouter.detaillistdormitory,
    component: DetailListDormitory,
  },
  { path: adminConfigRouter.studentTasks, component: StudentTasks },
  { path: adminConfigRouter.inbox, component: Inbox },
  { path: adminConfigRouter.program, component: Program },
  { path: adminConfigRouter.detailProgram, component: DetailProgram },
  { path: adminConfigRouter.dataStudent, component: DataStudent },
  { path: adminConfigRouter.dataStudent, component: DataStudent },
  { path: adminConfigRouter.sport, component: Sport },
  { path: adminConfigRouter.detailSportEvent, component: DetailSport },
  { path: adminConfigRouter.managerUser, component: ManagerUser },
  { path: adminConfigRouter.profile, component: ProfileUser },
  { path: adminConfigRouter.notification, component: Notification },
];
export { dormsRoutes, schRoutes, adminRoutes };
