export const configRouter = {
  home: "/",
  login: "/login",
  detailUniversity: "/university/:universityId",
  detailMajor: "/university/major/:majorId",
  detailStudent: "/university/student/:studentId",
  dormitory: "/dormitory",
  studentRoom: "/dormitory/:dormId",
  detailRoom: "/dormitory/room/:roomId",
  studentTasks: "/tasks",
  inbox: "/inbox",
  scholarships: "/scholarships",
  passport: "/passport",
  detailPassport: "/passport/list/:year",
  detailInfoVisa: "/passport/visa/:visaId",
  detailInfoPassport: "/passport/detailpassport/:userId",
  healthcare: "/healthcare",
  electricityWater: "/electricitywater",
  electricityLookup: "/electricity/:electricityId",
  waterLookup: "/water/:waterId",
  program: "/program",
  detailProgram: "/detailProgram/:detailProgramId",
  dataStudent: "/data",
};
